# Generated by Django 5.1.6 on 2025-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_orders_options_orders_unique_draft_per_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
