# Generated by Django 5.1.6 on 2025-04-10 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_delete_product_alter_authuser_options_services_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 10), verbose_name='Дата'),
        ),
    ]
