# Generated by Django 5.1.6 on 2025-04-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_alter_authuser_options_and_more'),
    ]

    operations = [
    ]
