# Generated by Django 5.1.6 on 2025-04-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_auto_20250403_1707'),
    ]

    operations = [
    ]
