# Generated by Django 5.1.6 on 2025-04-20 19:09

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_services_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удален'), ('formed', 'Сформирован'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('table_number', models.PositiveIntegerField(default=0, help_text='Номер стола не может превышать 10', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Номер стола')),
                ('total_sum', models.PositiveIntegerField(default=0, verbose_name='Сумма заказа')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='bmstu_lab.authuser', verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_orders', to='bmstu_lab.authuser', verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'dish',
            },
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='orderservices',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderservices',
            name='guest_name',
            field=models.CharField(default='default', max_length=255, verbose_name='Имя гостя'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default=datetime.date, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.dish', verbose_name='Заявка'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('creator',), name='unique_draft_per_user'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
